# Generated by Django 3.0.7 on 2021-12-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='web_link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
