# Generated by Django 3.0.7 on 2021-12-27 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_team_web_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='google_link',
            new_name='instragam_link',
        ),
    ]
