# Generated by Django 3.0.7 on 2021-12-28 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
    ]
