# Generated by Django 3.0.7 on 2022-01-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=50, verbose_name='Mensaje')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('email', models.CharField(max_length=50, verbose_name='Correo')),
                ('subject', models.CharField(max_length=100, verbose_name='Asunto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'contacts',
                'ordering': ['-id'],
            },
        ),
    ]
