# Generated by Django 3.0.7 on 2022-01-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20220107_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=50, verbose_name='Mensaje'),
        ),
    ]
