# Generated by Django 3.0.7 on 2022-01-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20220107_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Nombre')),
                ('photo', models.ImageField(upload_to='inicio/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Inicio',
                'verbose_name_plural': 'Inicios',
                'db_table': 'inicio',
                'ordering': ['id'],
            },
        ),
    ]
