# Generated by Django 3.0.7 on 2022-01-11 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_inicio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inicio',
        ),
    ]
