# Generated by Django 3.0.7 on 2021-12-28 04:41

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_delete_category'),
        ('blogs', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='blogs/%Y/%m/%d/')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('description', ckeditor.fields.RichTextField()),
                ('facebook_link', models.URLField(blank=True, max_length=100, null=True)),
                ('twitter_link', models.URLField(blank=True, max_length=100, null=True)),
                ('instragam_link', models.URLField(blank=True, max_length=100, null=True)),
                ('web_link', models.URLField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('autor_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Team')),
                ('category_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Category')),
                ('comment_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Comment')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Post',
                'db_table': 'post',
                'ordering': ['id'],
            },
        ),
    ]
