# Generated by Django 3.0.7 on 2021-12-28 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20211227_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='autor_fk',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='category_fk',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='comment_fk',
            new_name='comment',
        ),
    ]
