# Generated by Django 3.0.7 on 2022-01-03 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
